SDIR="../../Part1/OfficeOpenXML-RELAXNG-Strict/"
TDIR="../../Part4/OfficeOpenXML-RELAXNG-Transitional/"
diff -U 10000 ${SDIR}DrawingML_Chart.rnc ${TDIR}DrawingML_Chart.rnc > DrawingML_Chart.rnc
diff -U 10000 ${SDIR}DrawingML_Chart_Drawing.rnc ${TDIR}DrawingML_Chart_Drawing.rnc > DrawingML_Chart_Drawing.rnc
diff -U 10000 ${SDIR}DrawingML_Diagram_Colors.rnc ${TDIR}DrawingML_Diagram_Colors.rnc > DrawingML_Diagram_Colors.rnc
diff -U 10000 ${SDIR}DrawingML_Diagram_Data.rnc ${TDIR}DrawingML_Diagram_Data.rnc > DrawingML_Diagram_Data.rnc
diff -U 10000 ${SDIR}DrawingML_Diagram_Layout_Definition.rnc ${TDIR}DrawingML_Diagram_Layout_Definition.rnc > DrawingML_Diagram_Layout_Definition.rnc
diff -U 10000 ${SDIR}DrawingML_Diagram_Style.rnc ${TDIR}DrawingML_Diagram_Style.rnc > DrawingML_Diagram_Style.rnc
diff -U 10000 ${SDIR}DrawingML_Table_Styles.rnc ${TDIR}DrawingML_Table_Styles.rnc > DrawingML_Table_Styles.rnc
diff -U 10000 ${SDIR}DrawingML_Theme.rnc ${TDIR}DrawingML_Theme.rnc > DrawingML_Theme.rnc
diff -U 10000 ${SDIR}DrawingML_Theme_Override.rnc ${TDIR}DrawingML_Theme_Override.rnc > DrawingML_Theme_Override.rnc
diff -U 10000 ${SDIR}PresentationML_Comment_Authors.rnc ${TDIR}PresentationML_Comment_Authors.rnc > PresentationML_Comment_Authors.rnc
diff -U 10000 ${SDIR}PresentationML_Comments.rnc ${TDIR}PresentationML_Comments.rnc > PresentationML_Comments.rnc
diff -U 10000 ${SDIR}PresentationML_Handout_Master.rnc ${TDIR}PresentationML_Handout_Master.rnc > PresentationML_Handout_Master.rnc
diff -U 10000 ${SDIR}PresentationML_Notes_Master.rnc ${TDIR}PresentationML_Notes_Master.rnc > PresentationML_Notes_Master.rnc
diff -U 10000 ${SDIR}PresentationML_Notes_Slide.rnc ${TDIR}PresentationML_Notes_Slide.rnc > PresentationML_Notes_Slide.rnc
diff -U 10000 ${SDIR}PresentationML_Presentation.rnc ${TDIR}PresentationML_Presentation.rnc > PresentationML_Presentation.rnc
diff -U 10000 ${SDIR}PresentationML_Presentation_Properties.rnc ${TDIR}PresentationML_Presentation_Properties.rnc > PresentationML_Presentation_Properties.rnc
diff -U 10000 ${SDIR}PresentationML_Slide.rnc ${TDIR}PresentationML_Slide.rnc > PresentationML_Slide.rnc
diff -U 10000 ${SDIR}PresentationML_Slide_Layout.rnc ${TDIR}PresentationML_Slide_Layout.rnc > PresentationML_Slide_Layout.rnc
diff -U 10000 ${SDIR}PresentationML_Slide_Master.rnc ${TDIR}PresentationML_Slide_Master.rnc > PresentationML_Slide_Master.rnc
diff -U 10000 ${SDIR}PresentationML_Slide_Synchronization_Data.rnc ${TDIR}PresentationML_Slide_Synchronization_Data.rnc > PresentationML_Slide_Synchronization_Data.rnc
diff -U 10000 ${SDIR}PresentationML_User-Defined_Tags.rnc ${TDIR}PresentationML_User-Defined_Tags.rnc > PresentationML_User-Defined_Tags.rnc
diff -U 10000 ${SDIR}PresentationML_View_Properties.rnc ${TDIR}PresentationML_View_Properties.rnc > PresentationML_View_Properties.rnc
diff -U 10000 ${SDIR}Shared_Additional_Characteristics.rnc ${TDIR}Shared_Additional_Characteristics.rnc > Shared_Additional_Characteristics.rnc
diff -U 10000 ${SDIR}Shared_Bibliography.rnc ${TDIR}Shared_Bibliography.rnc > Shared_Bibliography.rnc
diff -U 10000 ${SDIR}Shared_Custom_File_Properties.rnc ${TDIR}Shared_Custom_File_Properties.rnc > Shared_Custom_File_Properties.rnc
diff -U 10000 ${SDIR}Shared_Custom_XML_Data_Storage_Properties.rnc ${TDIR}Shared_Custom_XML_Data_Storage_Properties.rnc > Shared_Custom_XML_Data_Storage_Properties.rnc
diff -U 10000 ${SDIR}Shared_Extended_File_Properties.rnc ${TDIR}Shared_Extended_File_Properties.rnc > Shared_Extended_File_Properties.rnc
diff -U 10000 ${SDIR}SpreadsheetML_Calculation_Chain.rnc ${TDIR}SpreadsheetML_Calculation_Chain.rnc > SpreadsheetML_Calculation_Chain.rnc
diff -U 10000 ${SDIR}SpreadsheetML_Chartsheet.rnc ${TDIR}SpreadsheetML_Chartsheet.rnc > SpreadsheetML_Chartsheet.rnc
diff -U 10000 ${SDIR}SpreadsheetML_Comments.rnc ${TDIR}SpreadsheetML_Comments.rnc > SpreadsheetML_Comments.rnc
diff -U 10000 ${SDIR}SpreadsheetML_Connections.rnc ${TDIR}SpreadsheetML_Connections.rnc > SpreadsheetML_Connections.rnc
diff -U 10000 ${SDIR}SpreadsheetML_Custom_XML_Mappings.rnc ${TDIR}SpreadsheetML_Custom_XML_Mappings.rnc > SpreadsheetML_Custom_XML_Mappings.rnc
diff -U 10000 ${SDIR}SpreadsheetML_Dialogsheet.rnc ${TDIR}SpreadsheetML_Dialogsheet.rnc > SpreadsheetML_Dialogsheet.rnc
diff -U 10000 ${SDIR}SpreadsheetML_Drawing.rnc ${TDIR}SpreadsheetML_Drawing.rnc > SpreadsheetML_Drawing.rnc
diff -U 10000 ${SDIR}SpreadsheetML_External_Workbook_References.rnc ${TDIR}SpreadsheetML_External_Workbook_References.rnc > SpreadsheetML_External_Workbook_References.rnc
diff -U 10000 ${SDIR}SpreadsheetML_Metadata.rnc ${TDIR}SpreadsheetML_Metadata.rnc > SpreadsheetML_Metadata.rnc
diff -U 10000 ${SDIR}SpreadsheetML_Pivot_Table.rnc ${TDIR}SpreadsheetML_Pivot_Table.rnc > SpreadsheetML_Pivot_Table.rnc
diff -U 10000 ${SDIR}SpreadsheetML_Pivot_Table_Cache_Definition.rnc ${TDIR}SpreadsheetML_Pivot_Table_Cache_Definition.rnc > SpreadsheetML_Pivot_Table_Cache_Definition.rnc
diff -U 10000 ${SDIR}SpreadsheetML_Pivot_Table_Cache_Records.rnc ${TDIR}SpreadsheetML_Pivot_Table_Cache_Records.rnc > SpreadsheetML_Pivot_Table_Cache_Records.rnc
diff -U 10000 ${SDIR}SpreadsheetML_Query_Table.rnc ${TDIR}SpreadsheetML_Query_Table.rnc > SpreadsheetML_Query_Table.rnc
diff -U 10000 ${SDIR}SpreadsheetML_Shared_String_Table.rnc ${TDIR}SpreadsheetML_Shared_String_Table.rnc > SpreadsheetML_Shared_String_Table.rnc
diff -U 10000 ${SDIR}SpreadsheetML_Shared_Workbook_Revision_Headers.rnc ${TDIR}SpreadsheetML_Shared_Workbook_Revision_Headers.rnc > SpreadsheetML_Shared_Workbook_Revision_Headers.rnc
diff -U 10000 ${SDIR}SpreadsheetML_Shared_Workbook_Revision_Log.rnc ${TDIR}SpreadsheetML_Shared_Workbook_Revision_Log.rnc > SpreadsheetML_Shared_Workbook_Revision_Log.rnc
diff -U 10000 ${SDIR}SpreadsheetML_Shared_Workbook_User_Data.rnc ${TDIR}SpreadsheetML_Shared_Workbook_User_Data.rnc > SpreadsheetML_Shared_Workbook_User_Data.rnc
diff -U 10000 ${SDIR}SpreadsheetML_Single_Cell_Table_Definitions.rnc ${TDIR}SpreadsheetML_Single_Cell_Table_Definitions.rnc > SpreadsheetML_Single_Cell_Table_Definitions.rnc
diff -U 10000 ${SDIR}SpreadsheetML_Styles.rnc ${TDIR}SpreadsheetML_Styles.rnc > SpreadsheetML_Styles.rnc
diff -U 10000 ${SDIR}SpreadsheetML_Table_Definitions.rnc ${TDIR}SpreadsheetML_Table_Definitions.rnc > SpreadsheetML_Table_Definitions.rnc
diff -U 10000 ${SDIR}SpreadsheetML_Volatile_Dependencies.rnc ${TDIR}SpreadsheetML_Volatile_Dependencies.rnc > SpreadsheetML_Volatile_Dependencies.rnc
diff -U 10000 ${SDIR}SpreadsheetML_Workbook.rnc ${TDIR}SpreadsheetML_Workbook.rnc > SpreadsheetML_Workbook.rnc
diff -U 10000 ${SDIR}SpreadsheetML_Worksheet.rnc ${TDIR}SpreadsheetML_Worksheet.rnc > SpreadsheetML_Worksheet.rnc
diff -U 10000 ${SDIR}WordprocessingML_Comments.rnc ${TDIR}WordprocessingML_Comments.rnc > WordprocessingML_Comments.rnc
diff -U 10000 ${SDIR}WordprocessingML_Document_Settings.rnc ${TDIR}WordprocessingML_Document_Settings.rnc > WordprocessingML_Document_Settings.rnc
diff -U 10000 ${SDIR}WordprocessingML_Endnotes.rnc ${TDIR}WordprocessingML_Endnotes.rnc > WordprocessingML_Endnotes.rnc
diff -U 10000 ${SDIR}WordprocessingML_Font_Table.rnc ${TDIR}WordprocessingML_Font_Table.rnc > WordprocessingML_Font_Table.rnc
diff -U 10000 ${SDIR}WordprocessingML_Footer.rnc ${TDIR}WordprocessingML_Footer.rnc > WordprocessingML_Footer.rnc
diff -U 10000 ${SDIR}WordprocessingML_Footnotes.rnc ${TDIR}WordprocessingML_Footnotes.rnc > WordprocessingML_Footnotes.rnc
diff -U 10000 ${SDIR}WordprocessingML_Glossary_Document.rnc ${TDIR}WordprocessingML_Glossary_Document.rnc > WordprocessingML_Glossary_Document.rnc
diff -U 10000 ${SDIR}WordprocessingML_Header.rnc ${TDIR}WordprocessingML_Header.rnc > WordprocessingML_Header.rnc
diff -U 10000 ${SDIR}WordprocessingML_Mail_Merge_Recipient_Data.rnc ${TDIR}WordprocessingML_Mail_Merge_Recipient_Data.rnc > WordprocessingML_Mail_Merge_Recipient_Data.rnc
diff -U 10000 ${SDIR}WordprocessingML_Main_Document.rnc ${TDIR}WordprocessingML_Main_Document.rnc > WordprocessingML_Main_Document.rnc
diff -U 10000 ${SDIR}WordprocessingML_Numbering_Definitions.rnc ${TDIR}WordprocessingML_Numbering_Definitions.rnc > WordprocessingML_Numbering_Definitions.rnc
diff -U 10000 ${SDIR}WordprocessingML_Style_Definitions.rnc ${TDIR}WordprocessingML_Style_Definitions.rnc > WordprocessingML_Style_Definitions.rnc
diff -U 10000 ${SDIR}WordprocessingML_Web_Settings.rnc ${TDIR}WordprocessingML_Web_Settings.rnc > WordprocessingML_Web_Settings.rnc
diff -U 10000 ${SDIR}any.rnc ${TDIR}any.rnc > any.rnc
diff -U 10000 ${SDIR}dml-chart.rnc ${TDIR}dml-chart.rnc > dml-chart.rnc
diff -U 10000 ${SDIR}dml-chartDrawing.rnc ${TDIR}dml-chartDrawing.rnc > dml-chartDrawing.rnc
diff -U 10000 ${SDIR}dml-diagram.rnc ${TDIR}dml-diagram.rnc > dml-diagram.rnc
diff -U 10000 ${SDIR}dml-lockedCanvas.rnc ${TDIR}dml-lockedCanvas.rnc > dml-lockedCanvas.rnc
diff -U 10000 ${SDIR}dml-main.rnc ${TDIR}dml-main.rnc > dml-main.rnc
diff -U 10000 ${SDIR}dml-picture.rnc ${TDIR}dml-picture.rnc > dml-picture.rnc
diff -U 10000 ${SDIR}dml-spreadsheetDrawing.rnc ${TDIR}dml-spreadsheetDrawing.rnc > dml-spreadsheetDrawing.rnc
diff -U 10000 ${SDIR}dml-wordprocessingDrawing.rnc ${TDIR}dml-wordprocessingDrawing.rnc > dml-wordprocessingDrawing.rnc
diff -U 10000 ${SDIR}pml.rnc ${TDIR}pml.rnc > pml.rnc
diff -U 10000 ${SDIR}shared-additionalCharacteristics.rnc ${TDIR}shared-additionalCharacteristics.rnc > shared-additionalCharacteristics.rnc
diff -U 10000 ${SDIR}shared-bibliography.rnc ${TDIR}shared-bibliography.rnc > shared-bibliography.rnc
diff -U 10000 ${SDIR}shared-commonSimpleTypes.rnc ${TDIR}shared-commonSimpleTypes.rnc > shared-commonSimpleTypes.rnc
diff -U 10000 ${SDIR}shared-customXmlDataProperties.rnc ${TDIR}shared-customXmlDataProperties.rnc > shared-customXmlDataProperties.rnc
diff -U 10000 ${SDIR}shared-customXmlSchemaProperties.rnc ${TDIR}shared-customXmlSchemaProperties.rnc > shared-customXmlSchemaProperties.rnc
diff -U 10000 ${SDIR}shared-documentPropertiesCustom.rnc ${TDIR}shared-documentPropertiesCustom.rnc > shared-documentPropertiesCustom.rnc
diff -U 10000 ${SDIR}shared-documentPropertiesExtended.rnc ${TDIR}shared-documentPropertiesExtended.rnc > shared-documentPropertiesExtended.rnc
diff -U 10000 ${SDIR}shared-documentPropertiesVariantTypes.rnc ${TDIR}shared-documentPropertiesVariantTypes.rnc > shared-documentPropertiesVariantTypes.rnc
diff -U 10000 ${SDIR}shared-math.rnc ${TDIR}shared-math.rnc > shared-math.rnc
diff -U 10000 ${SDIR}shared-relationshipReference.rnc ${TDIR}shared-relationshipReference.rnc > shared-relationshipReference.rnc
diff -U 10000 ${SDIR}sml.rnc ${TDIR}sml.rnc > sml.rnc
diff -U 10000 ${SDIR}wml.rnc ${TDIR}wml.rnc > wml.rnc
diff -U 10000 ${SDIR}xml.rnc ${TDIR}xml.rnc > xml.rnc